### ISSUE TITLE
How to activate TensorRT via API call?

### ISSUE THREAD

**Issue by DennLie** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#108]
I created some TensorRT engine profiles and would like to use them through the API. 
For example this is the JSON call i make from Unity:
JsonString:  {"denoising_strength":1.0,"mask_blur":4,"inpaint_full_res":true,"alwayson_scripts":{"Asymmetric tiling":{"args":[{"active":true,"tileX":true,"tileY":false,"startStep":0,"stopStep":-1}]},"ADetailer":{"args":[{"ad_model":"face_yolov8n.pt"}]}},"prompt":":1.3)","width":2048,"height":1024,"hr_scale":2,"hr_upscaler":"ESRGAN_4x","steps":18,"cfg_scale":7,"negative_prompt":"(worst quality, low quality, normal quality, bad quality:1.4), (lowres:1.3), (extra fingers, missing fingers:1.2), (poorly rendered hands:1.2), (mutation:1.1), (mutated hands:1.3), (deformed iris, deformed pupils:1.1), watermark, missing arms, missing hands, (long neck:1.4), (poorly drawn:1.3), (poorly drawn eyes:1.2), (poorly drawn hands:1.3), (poorly drawn iris:1.2), (poorly drawn pupils:1.2), (blurry:1.1),","sampler_index":"Euler a","script_name":"One Button Prompt","script_args":[5,"all","all","all","( A dog.:1.8)","","(unaestheticXL_AYv1:0.7),(worst quality, low quality, normal quality, bad quality:1.4), (lowres:1.3), (extra fingers, missing fingers:1.2), (poorly rendered hands:1.2), (mutation:1.1), (mutated hands:1.3), (deformed iris, deformed pupils:1.1), watermark, missing arms, missing hands, (long neck:1.4), (poorly drawn:1.3), (poorly drawn eyes:1.2), (poorly drawn hands:1.3), (poorly drawn iris:1.2), (poorly drawn pupils:1.2), (blurry:1.1),","1","none",false,"","","comma","( A dog.:1.8)",true,"",20,"all","all","all","all",0]}
UnityEngine.Debug:Log (object)

Without the TensorRT its working fine but when i activate it on auto1111 interface i get following error:

*** API error: POST: http://localhost:7860/sdapi/v1/txt2img {'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'No valid profile found. Please go to the TensorRT tab and generate an engine with the necessary profile. If using hires.fix, you need an engine for both the base and upscaled resolutions. Otherwise, use the default (torch) U-Net.'}
    Traceback (most recent call last):
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "A:\stable-diffusion-webui-dev\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "A:\stable-diffusion-webui-dev\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "A:\stable-diffusion-webui-dev\modules\api\api.py", line 378, in text2imgapi
        processed = scripts.scripts_txt2img.run(p, *p.script_args) # Need to pass args as list here
      File "A:\stable-diffusion-webui-dev\modules\scripts.py", line 605, in run
        processed = script.run(p, *script_args)
      File "A:\stable-diffusion-webui-dev\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 1075, in run
        processed = process_images(p)
      File "A:\stable-diffusion-webui-dev\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "A:\stable-diffusion-webui-dev\modules\processing.py", line 869, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "A:\stable-diffusion-webui-dev\modules\processing.py", line 1145, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "A:\stable-diffusion-webui-dev\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "A:\stable-diffusion-webui-dev\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "A:\stable-diffusion-webui-dev\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "A:\stable-diffusion-webui-dev\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "A:\stable-diffusion-webui-dev\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "A:\stable-diffusion-webui-dev\modules\sd_unet.py", line 89, in UNetModel_forward
        return current_unet.forward(x, timesteps, context, *args, **kwargs)
      File "A:\stable-diffusion-webui-dev\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 87, in forward
        self.switch_engine(feed_dict)
      File "A:\stable-diffusion-webui-dev\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 108, in switch_engine
        raise ValueError(
    ValueError: No valid profile found. Please go to the TensorRT tab and generate an engine with the necessary profile. If using hires.fix, you need an engine for both the base and upscaled resolutions. Otherwise, use the default (torch) U-Net.

I am not using hires.fix, so i guess i need to somehow activate the tensorrt profile also in the Json call. This is the example call but neither there or somewhere else i found any information about how to do it.
<img width="284" alt="image" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/50552332/6f7e4c55-c8b5-454d-97ff-08f440c5c563">

**Comment by DennLie** [comment]
Rebuilded a dynamic one and it worked on that one. I wonder why the static one with the right resolution gave me errors but at least it is working.
