### ISSUE TITLE
Error loading script: trt.py

### ISSUE THREAD

**Issue by thomasgaragan** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#127]
I saw this was addressed last week and I followed the guide linked here in a previous thread.

https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566

However, after reinstalling 2 times, i'm still having issues. Any help would be greatly appreciated!
Here is the print out in the terminal:

venv "E:\sd.webui\webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0-209-g7d60076b
Commit hash: 7d60076b8b275771a1aa98f017aff845ef68d964
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 8, in <module>
        import ui_trt
      File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 16, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 279, in <module>
        modelmanager = ModelManager()
      File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 35, in __init__
        self.update()
      File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 69, in update
        for base_model, models in base_models.items():
    RuntimeError: dictionary changed size during iteration

---
Exception ignored in: <function ModelManager.__del__ at 0x000001E19C427D00>
Traceback (most recent call last):
  File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 90, in __del__
    self.update()
  File "E:\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 69, in update
    for base_model, models in base_models.items():
RuntimeError: dictionary changed size during iteration
Loading weights [70229e1d56] from E:\sd.webui\webui\models\Stable-diffusion\juggernautXL_version5.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.6s (prepare environment: 3.7s, import torch: 2.7s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.0s, create ui: 0.4s, gradio launch: 0.7s).
Creating model from config: E:\sd.webui\webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 5.8s (load weights from disk: 1.4s, create model: 0.7s, apply weights to model: 3.2s, calculate empty prompt: 0.2s).

**Comment by thomasgaragan** [comment]
Update

I showed the terminal printout to Chat GPT and had it explain to me what was going wrong. 
It told me to edit this line of code in the model_manager.py file like this:

original: `for base_model, models in base_models.items():`

new: `for base_model, models in list(base_models.items()):`

I don't know anything about coding, so I'm not sure what the technicalities of this are, but it seems to have worked! 
The Tensorrt tab has reappeared and i'm getting some greatly increased speeds!

**Comment by murkinhustla** [comment]
> Update
> 
> I showed the terminal printout to Chat GPT and had it explain to me what was going wrong. It told me to edit this line of code in the model_manager.py file like this:
> 
> original: `for base_model, models in base_models.items():`
> 
> new: `for base_model, models in list(base_models.items()):`
> 
> I don't know anything about coding, so I'm not sure what the technicalities of this are, but it seems to have worked! The Tensorrt tab has reappeared and i'm getting some greatly increased speeds!

I was about to do the same thing, been banging my head against the wall doing fresh installs. ChatGPT is truly insane. 

Thank you for posting!
