### ISSUE TITLE
error when trying to convert Lora 

### ISSUE THREAD

**Issue by deulseolae** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#151]
Traceback (most recent call last):
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable diffusion web ui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable diffusion web ui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 197, in export_lora_to_trt
    lora_model = available_lora_models[lora_name]
KeyError: 'Rabbit'

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/146948801/06ca2f94-4b25-4f11-957c-3fc418b674e9)

**Comment by SakuraKoi** [comment]
experienced this bug today and found what caused it and how to make it works
You needs rename your lora model file to match the string behind `KeyError: `
