### ISSUE TITLE
img2img broken when switching to another model

### ISSUE THREAD

**Issue by 4lt3r3go** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#16]
i figured how to make RT things work 
but now for some reasons i can't use other ckpts in img2img tab only.
I can only use the converted RT model, otherwise i get this error:

```
 Traceback (most recent call last):
      File "F:\SD\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\SD\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\SD\webui\modules\img2img.py", line 208, in img2img
        processed = process_images(p)
      File "F:\SD\webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "F:\SD\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\SD\webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "F:\SD\webui\modules\processing.py", line 1528, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "F:\SD\webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\SD\webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "F:\SD\webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\SD\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\SD\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "F:\SD\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\SD\webui\modules\sd_samplers_cfg_denoiser.py", line 201, in forward
        devices.test_for_nans(x_out, "unet")
      File "F:\SD\webui\modules\devices.py", line 136, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
```

**Comment by atimogus** [comment]
i get the same error, did you fix it
