### ISSUE TITLE
tensor for lora - error

### ISSUE THREAD

**Issue by kalle07** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#172]
so finaly tensor models created for SDXL models ... all running fine and ist much faster than without   thx  ;)

but i have an error for creating SDXL-loras

up here it every line nearly same issue

ERROR:root:Failed to add Constant /out/out.0/Constant_output_0

Add Constant /out/out.0/Constant_1_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_1_output_0

Add Constant /out/out.0/Constant_2_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_2_output_0

Finished refit. Dumping result to disk.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-A1111-DEV\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 262, in export_lora_to_trt
    engine.refit(onnx_base_path, onnx_lora_path, dump_refit_path=trt_lora_path)
  File "D:\stable-A1111-DEV\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 277, in refit
    save_file(
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\safetensors\numpy.py", line 74, in save_file
    if not _is_little_endian(tensor):
  File "C:\ProgramData\anaconda3\envs\stable-diffusion-webui\lib\site-packages\safetensors\numpy.py", line 167, in _is_little_endian
    byteorder = tensor.dtype.byteorder
AttributeError: 'NoneType' object has no attribute 'dtype'
No ONNX file found. Exporting ONNX...
Disabling attention optimization

**Comment by kalle07** [comment]
it even dont work
