### ISSUE TITLE
SDXL Lora error , AttributeError: 'Variable' object has no attribute 'values' 

### ISSUE THREAD

**Issue by sahil1572** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#173]
Applying LoRAs: ['lora:colorpx:1']
```
*** Error running process: J:\x\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "J:\x\stable-diffusion-webui\modules\scripts.py", line 710, in process
        script.process(p, *script_args)
      File "J:\x\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 191, in process
        self.get_loras(p)
      File "J:\x\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 238, in get_loras
        refit_dict = apply_loras(base_path, lora_pathes, lora_scales)
      File "J:\x\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\lora.py", line 32, in apply_loras
        add_to_map(refit_dict, name, n.outputs[0].values)
    AttributeError: 'Variable' object has no attribute 'values'
```

---
Loading TensorRT engine: J:\x\stable-diffusion-webui\models\Unet-trt\copaxTimelessxlSDXL1_v7_6047dfce_cc86_sample=2x4x128x128-timesteps=2-encoder_hidden_states=2x77x2048-y=2x2816.trt

Loaded Profile: 0
        sample = [(2, 4, 128, 128), (2, 4, 128, 128), (2, 4, 128, 128)]
        timesteps = [(2,), (2,), (2,)]
        encoder_hidden_states = [(2, 77, 2048), (2, 77, 2048), (2, 77, 2048)]
        y = [(2, 2816), (2, 2816), (2, 2816)]
        latent = [(2, 4, 128, 128), (2, 4, 128, 128), (2, 4, 128, 128)]

100%| 15/15 [00:02<00:00,  5.81it/s]

i have already exported model and the lora to tensorsrt

**Comment by kalle07** [comment]
hey ...

you are already run the tensor checkpoint alone ?

You were able to create a Lora tensor ? 
anny special, i have problems on loras  (to generate ceckpoints all running fine)

**Comment by kalle07** [comment]
ok 

 lora_v2 the lora is tcreated , but 5GB of an 200mb lora ?

and same error that [sahil1572](https://github.com/sahil1572) mentioned

**Comment by qybing** [comment]
I am also facing the same issue. Do you have any solutions?

**Comment by kalle07** [comment]
nop .. but we must write here a lot, that it comes to there attantion  ;)

**Comment by chengzeyi** [comment]
@sahil1572 
Hi, friend！I know you are suffering great pain from using `TRT` with `diffusers`.

So why not choose my totally **open-sourced** alternative: [`stable-fast`](https://github.com/chengzeyi/stable-fast)?
It's on par with `TRT` on inference speed, faster than `torch.compile` and `AITemplate`, and is super dynamic and flexible, supporting **ALL** SD models and **LoRA** and **ControlNet** out of the box!

[![](https://mermaid.ink/img/pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1?type=png)](https://mermaid.live/edit#pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1)

**Comment by kalle07** [comment]
interesting...

is it already implemented in automatic1111, to choose a model or lora for building the tensor model ?
or you have a small gui , i think most dont want doo it by hand   ;)

**Comment by chengzeyi** [comment]
@bogdanstoian1988 sd next's dev branch now officially supports it. Bu a1111 hasn't

**Comment by kalle07** [comment]
helloo ... seems Nvida only will earn monay  :D

**Comment by bogdanstoian1988** [comment]
> @bogdanstoian1988 sd next's dev branch now officially supports it. But a1111 hasn't

sd next doesn't support trained models, like the ones from Civitai... You know we all want it for a1111 :)

**Comment by andreacostigliolo** [comment]
I am also facing the same issue. Do you have any solutions?

**Comment by kalle07** [comment]
HELLO AGAIN ^^

any progress ?
