### ISSUE TITLE
Error exporting default engine using TensorRT

### ISSUE THREAD

**Issue by oldtian123** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#179]
When I exported the TensorRT default engine, I encountered the following message, so I checked the terminal error message. 

info No ONNX file found. Exporting ONNX... Please check the progress in the terminal.

The following is the terminal error message.

ERROR:root:Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
Traceback (most recent call last):
  File "C:\共享\sd-webui-aki-v4.2\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 84, in export_onnx
    torch.onnx.export(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\onnx\utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\onnx\utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\onnx\utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\jit\_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\modules\sd_unet.py", line 91, in UNetModel_forward
    return original_forward(self, x, timesteps, context, *args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 984, in forward
    emb = self.time_embed(t_emb)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\extensions-builtin\Lora\networks.py", line 493, in network_Linear_forward
    return originals.Linear_forward(self, input)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\共享\sd-webui-aki-v4.2\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\共享\sd-webui-aki-v4.2\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "C:\共享\sd-webui-aki-v4.2\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "C:\共享\sd-webui-aki-v4.2\python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by 82604716** [comment]
start up only  webui.bat --listen  is ok

**Comment by chengzeyi** [comment]
@oldtian123 
Hi, friend！I know you are suffering great pain from using `TRT` with `diffusers`.

So why not choose my totally **open-sourced** alternative: [`stable-fast`](https://github.com/chengzeyi/stable-fast)?
It's on par with `TRT` on inference speed, faster than `torch.compile` and `AITemplate`, and is super dynamic and flexible, supporting **ALL** SD models and **LoRA** and **ControlNet** out of the box!

[![](https://mermaid.ink/img/pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1?type=png)](https://mermaid.live/edit#pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1)

**Comment by kanekasim0** [comment]
Your webui is located in the C:\shared folder. When using this plugin, the file path cannot contain Chinese characters.
你的webui放在了C:\共享 这个文件夹下，用这个插件的时候文件路径不能有中文

**Comment by bigmover** [comment]
> @oldtian123 Hi, friend！I know you are suffering great pain from using `TRT` with `diffusers`.
> 
> So why not choose my totally **open-sourced** alternative: [`stable-fast`](https://github.com/chengzeyi/stable-fast)? It's on par with `TRT` on inference speed, faster than `torch.compile` and `AITemplate`, and is super dynamic and flexible, supporting **ALL** SD models and **LoRA** and **ControlNet** out of the box!
> 
> [![](https://camo.githubusercontent.com/e81e678d2e3175ae8d3c611b2d404ba982a98922c7ce9d47501ee814c947097f/68747470733a2f2f6d65726d6169642e696e6b2f696d672f70616b6f3a654e7056556b32506d7a41515f53736a53314575514779794a4d4268705a573268783536326556516462324841516177424461797a545a5278482d765361704b50646836387a7a79655f4e7859343170695a5673743773707258774a74373066614b4a394366764f57484a2d76384b3632306c397554594457685f5835464671725f784949466d6c4a6f4b5143443170737569563773466f416a5668545f42622d5148655830456b5751535a53435f68424d4442655a706446444c6872666f4a547a7a6e6b67574a47435f4b7759646b58366a564f434a34593574427369676f335748536d476c57497a326f6c2d385654664f495f6d39636b586247766c56514a447752443835357245654b4f335265736b2d707277384e796159676f4277315272644f4d75415178382d516373366c6c727047437838694c38345269457a77634973736a36416f524941384c54355a7843617945366f324e4f386d4e57774f74385a4a56675a596f364f746f6a586b34654c4e2d315533725052326f59677463787363767972734c55375f6b3939614663706b5a59656a432d526f734b55513370695f7a747555657556382d444634376c535f38597364417a313450377679634e69656b7a3730664b6d33526832636172655244565f463658424b547a6d6d527a71646a3567646a32315469794c763069665274576375556d54724772455a3953396a706e3847364f376e78324e46377075795f67484d4f6250313f747970653d706e67)](https://mermaid.live/edit#pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1)

TRT is slower than  Vanilla torch in stable-diffusion Webui?

**Comment by jangrewe** [comment]
> TRT is slower than Vanilla torch in stable-diffusion Webui?

Please learn to read graphs properly - that means: including the title 😉
