### ISSUE TITLE
Error loading script: trt.py

### ISSUE THREAD

**Issue by Dartvauder** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#183]
Hi all. Please help who can. Previously, everything worked fine until I changed the name of the folder for models from SD to SD1.5. At first it stopped accepting unet files saying that the name was incorrect. I changed the name of the model itself. In the end, this error comes out. I tried reinstalling the extension. The same

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 10, in <module>
        import ui_trt
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 16, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 221, in <module>
        modelmanager = ModelManager()
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 35, in __init__
        self.update()
      File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 69, in update
        for base_model, models in base_models.items():
    RuntimeError: dictionary changed size during iteration

---
Exception ignored in: <function ModelManager.__del__ at 0x000002106C6480D0>
Traceback (most recent call last):
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 89, in __del__
    self.update()
  File "D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 69, in update
    for base_model, models in base_models.items():
RuntimeError: dictionary changed size during iteration
Loading weights [879db523c3] from D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\models\Stable-diffusion\SD1.5\dreamshaper_8.safetensors
Running on local URL:  http://127.0.0.1:7860
Creating model from config: D:\OpenSource\NeuralNetworks\ImageVideoGeneration\webui\configs\v1-inference.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 21.3s (prepare environment: 2.9s, import torch: 9.1s, import gradio: 1.4s, setup paths: 0.8s, initialize shared: 0.1s, other imports: 0.7s, setup codeformer: 0.2s, load scripts: 5.1s, create ui: 0.4s, gradio launch: 0.7s).
Applying attention optimization: Doggettx... done.
Model loaded in 2.6s (load weights from disk: 0.6s, create model: 0.4s, apply weights to model: 1.3s, calculate empty prompt: 0.2s).

**Comment by Dartvauder** [comment]
Everything is already working for me. What helped me was deleting the old model.json file from the models/unet-trt folder.
