### ISSUE TITLE
I think I almost had a stroke turning SD_VAE on

### ISSUE THREAD

**Issue by banshek7** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#195]
Lol I couldnt figure out how my new glorious 13it/s with my potato 2060 card was suddenly ruined, even when selecting my new SD_VAE option to none, but for some reason I had to actually disable it in the user interface options completely to get back to ripping my pictures quickly again. 

Is there a way I can get sd vae to work with your tensor export stuff. Like could I just put it in my stable diffusion model folder and export it and then put it in VAE lol... Ugh sorry I just really want to finish this all off with that =(

**Comment by banshek7** [comment]
![00528-4037907555](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/11663406/2cf11f17-1e24-4fb9-a987-e11ba3a3c4d5)


I'll leave you with my last generation, courtesy of your awesome work here, I hope you can fix that or warn people if its repeatable because that was mind boggling to go from 13 to 1-3 with no explanation.  **using SD_VAE is fine, adding that back in had no ill effect**

**Comment by banshek7** [comment]
I just wanted to update that it seems worse than ever now that I exported a third one, I have to do some really gypsy stuff, switching back and forth on the model and unet drop downs, hitting refresh, and then all the sudden its working again like lol. Even sometimes now its printing the tensor field thing and going slow, or I was just having this insane print in the cmd, **I literally hit refresh on SD UNET one more time** and that was the tipping point of it going back to working again. 


`
To create a public link, set `share=True` in `launch()`.
Startup time: 46.9s (prepare environment: 20.4s, import torch: 3.6s, import gradio: 1.1s, setup paths: 1.3s, initialize shared: 0.2s, other imports: 0.9s, setup codeformer: 0.2s, load scripts: 4.9s, create ui: 12.9s, gradio launch: 0.6s, app_started_callback: 0.8s).
Traceback (most recent call last):
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks.py", line 392, in pages_html
    return refresh()
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks.py", line 400, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks.py", line 162, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks_checkpoints.py", line 35, in list_items
    yield self.create_item(name, index)
  File "C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\modules\ui_extra_networks_checkpoints.py", line 18, in create_item
    path, ext = os.path.splitext(checkpoint.filename)
AttributeError: 'NoneType' object has no attribute 'filename'
                                  Activating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading TensorRT engine: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Unet-trt\realisticVisionV60B1_v60B1VAE_d6aa28fb_cc75_sample=1x4x64x64+2x4x64x64+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt

Loaded Profile: 0
        sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 128, 128)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1945890048), (-1945887232), (-1945891072)]

 38%|███████████████████████████████▏                                                  | 19/50 [00:07<00:12,  2.57it/s]
Total progress:  19%|████████████▎                                                    | 19/100 [00:19<01:23,  1.03s/it]
Reusing loaded model realisticVisionV60B1_v60B1VAE.safetensors [e5f3cbc5f7] to load dreamshaper_8.safetensors [879db523c3]
Dectivating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading weights [879db523c3] from C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8.safetensors
Loading VAE weights specified in settings: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Weights loaded in 6.4s (send model to cpu: 0.1s, calculate hash: 0.9s, load weights from disk: 0.3s, apply weights to model: 4.4s, load VAE: 0.1s, move model to device: 0.4s).
Activating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading TensorRT engine: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Unet-trt\realisticVisionV60B1_v60B1VAE_d6aa28fb_cc75_sample=1x4x64x64+2x4x64x64+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt

Loaded Profile: 0
        sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 128, 128)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1946027008), (-1946027693), (-1946037504)]

Reusing loaded model dreamshaper_8.safetensors [879db523c3] to load realisticVisionV60B1_v60B1VAE.safetensors [e5f3cbc5f7]
Dectivating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading weights [e5f3cbc5f7] from C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV60B1_v60B1VAE.safetensors
Loading VAE weights specified in settings: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Weights loaded in 2.3s (send model to cpu: 0.1s, calculate hash: 1.0s, load weights from disk: 0.2s, apply weights to model: 0.4s, load VAE: 0.1s, move model to device: 0.5s).
Activating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading TensorRT engine: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Unet-trt\realisticVisionV60B1_v60B1VAE_d6aa28fb_cc75_sample=1x4x64x64+2x4x64x64+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt

Loaded Profile: 0
        sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 128, 128)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1946012160), (-1946013440), (-1946010368)]

Restoring base VAE
Applying attention optimization: xformers... done.
VAE weights loaded.
Loading VAE weights specified in settings: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
VAE weights loaded.
                                                                                                                       Dectivating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)                        | 0/50 [00:00<?, ?it/s]
Activating unet: [TRT] ClothingAdjuster3 (realisticVisionV60B1_v60B1VAE)
Loading TensorRT engine: C:\F Backup\AuTomAtic1111\stable-diffusion-webui\stable-diffusion-webui\models\Unet-trt\realisticVisionV60B1_v60B1VAE_d6aa28fb_cc75_sample=1x4x64x64+2x4x64x64+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt`



idk it kept looping crazy stuff like then, then like i said, hit refresh icon on the unet drop down one more time and the error was gone and it was going my top 13it/s again =(

**Comment by banshek7** [comment]
Its actually evolving over time, this is horrifying, I just spent 30 minutes dittling with the fucking pulldown unets and hitting refresh and then trying new args i was so desperate and finally about 9it/s clicked back on.   It seems to have a mind of its own, it feels that random, i sit here and its hard as hell to find a repeatable step now to get it to give me full speed. Sometimes it starts at 1it/s now. 

**Mind you before starting to export other models and loras, i could just spam generate at 13it/s, it seems to be some kind of mismatch between the model and unet or something, i really dont know, i just hope i can fix it or find a bigger clue **

**Comment by banshek7** [comment]
**My current and I guess final method for reaching usability now is I load up, now with these args** 
set COMMANDLINE_ARGS=--xformers --force-enable-xformers --theme dark   (I took out half vae)

Then my web UI loads with real modelV6, unet real model, & a VAE. 
If I were to generate its glitched at 1-3 it/s
I have to switch my model, set unet to none, and generate, 
Then I have to go back to my realV6 model, switch unet to automatic, refresh, then go back to my matching Unet TRT model, then with any luck its going at at least 9it/s and 2 it/s upscale, but I have to keep hitting refresh on the unet after each generation (sometimes, sometimes I can just keep generating at full speed)


 its beyond retarded, I want to punch it in the fucking face if it had one. I've never been more mad at a technical problem lmfao, because it seems to follow no logic, besides having built in A.I to drive me insane somehow.
