### ISSUE TITLE
Errors but TRT works, what is the point?

### ISSUE THREAD

**Issue by Adzido** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#219]
Every time I try to rerender anything (even without using TRT) I get this error: 

*** Error running process_batch: C:\Users\AdziOo\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "C:\Users\AdziOo\stable-diffusion-webui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\Users\AdziOo\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 302, in process_batch
        if self.idx != sd_unet.current_unet.profile_idx:
    AttributeError: 'NoneType' object has no attribute 'profile_idx'

How to fix it?

**Comment by rmcc3** [comment]
Looks like you don't have an engine trained. However, even with an engine trained, I have a lot of issues past this issue. 

`RuntimeError: The size of tensor a (96) must match the size of tensor b (128) at non-singleton dimension 3`

**Comment by coderCK2** [comment]
I think this happens when you have "None" selected in the unet selector. The code seems to check for a profile even in the case where you don't want to use one, which throws this error. It is annoying for when you are not using TRT, but it actually doesn't affect anything other than making noise in the console.

**Comment by Codyport** [comment]
Gah.  Thanks.  Now I feel dumb  =)

**Comment by EtienneDosSantos** [comment]
> I think this happens when you have "None" selected in the unet selector. The code seems to check for a profile even in the case where you don't want to use one, which throws this error. It is annoying for when you are not using TRT, but it actually doesn't affect anything other than making noise in the console.

Can confirm it only occurs, when "None" is selected in unet selector. It also doesn't happen, if the wrong engine is selected or the batch size exceeds the built engines'.

**Comment by Adzido** [comment]
How to fix it? I dont want this spam in console. I have this error also wtih "automatic" not only "none".

**Comment by EtienneDosSantos** [comment]
Editing line 302 in the file trt.py (find it under: \stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py) from
`if self.idx != sd_unet.current_unet.profile_idx:`
to
`if sd_unet.current_unet is not None and self.idx != sd_unet.current_unet.profile_idx:`
fixed it for me.

**Comment by PabloMontero** [comment]
Excellent!

On the other hand, what about this error message when starting A1111?

![Screenshot 2024-01-30 105327](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/22867200/29972660-a9af-41c3-81a2-d37a9afc9435)
