### ISSUE TITLE
TensorRT error when building engines

### ISSUE THREAD

**Issue by flzpfnove** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#223]
Everything works fine except for TensorRT (loads but gives errors when building engines)

I followed this guide to install TensorRT: https://nvidia.custhelp.com/app/answers/detail/a_id/5487

This is the full log from starting the WebUI to the error:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --xformers
Style database not found: E:\stable-diffusion-tensorrt\webui\styles.csv
Loading weights [6ce0161689] from E:\stable-diffusion-tensorrt\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\stable-diffusion-tensorrt\webui\configs\v1-inference.yaml
Startup time: 9.5s (prepare environment: 2.1s, import torch: 2.8s, import gradio: 1.0s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.6s, load scripts: 1.0s, create ui: 0.5s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 3.6s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 2.4s, calculate empty prompt: 0.1s).
Disabling attention optimization
Exporting v1-5-pruned-emaonly to TensorRT using - Batch Size: 1-1-4
Height: 512-512-768
Width: 512-512-768
Token Count: 75-75-150
Disabling attention optimization
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for E:\stable-diffusion-tensorrt\webui\models\Unet-onnx\v1-5-pruned-emaonly.onnx: E:\stable-diffusion-tensorrt\webui\models\Unet-trt\v1-5-pruned-emaonly_d7049739_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[!] Invalid inputs were provided to the optimization profile: {'encoder_hidden_states', 'sample', 'timesteps'}
    Note: Inputs available in the TensorRT network are: set()
Traceback (most recent call last):
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-tensorrt\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 126, in export_unet_to_trt
    ret = export_trt(
  File "E:\stable-diffusion-tensorrt\webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 231, in export_trt
    ret = engine.build(
  File "E:\stable-diffusion-tensorrt\webui\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 260, in build
    calib_profile = profile.fill_defaults(network[1]).to_trt(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\polygraphy\backend\trt\profile.py", line 190, in to_trt
    G_LOGGER.critical(
  File "E:\stable-diffusion-tensorrt\system\python\lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid inputs were provided to the optimization profile: {'encoder_hidden_states', 'sample', 'timesteps'}
Note: Inputs available in the TensorRT network are: set()
```

(I'm using xformers but I get the same error even without it)

**Comment by flzpfnove** [comment]
i switched to another model and it worked, i will be assuming that the issue was with the "emaonly" model (for better inference but doesn't support finetuning and probably also doesn't support being converted to a tensorrt engine)
