### ISSUE TITLE
[v0.2.0] ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by devildelta** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#230]
Input Prompt Length: 75

Generation Parameters:
- Width: 320
- Height: 640
- having 4 profiles generated by v0.1.0
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/9845381/30c3edbf-c8df-4921-8ca9-9a6772ddd163)

Error Log
```
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\sd_unet.py", line 89, in UNetModel_forward
        return current_unet.forward(x, timesteps, context, *args, **kwargs)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 70, in forward
        self.engine.allocate_buffers(feed_dict)
      File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 304, in allocate_buffers
        tuple(shape), dtype=numpy_to_torch_dtype_dict[dtype]
    ValueError: __len__() should return >= 0
```

Image can be generated when SD Unet is disabled explicitly.

**Comment by ItsSkynet** [comment]
what i noticed with the new update is that your profile that loads has to cover the whole spectrum including your max resolution set by "hi-res fix". i don't know if you are using that, but force rebuild your profile might not hurt.

**Comment by devildelta** [comment]
After removing Unet folder contents and restarted the instance, when I tried to regenerate the default engine, the `Expected all tensors to be on the same device` occurs.

```
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --opt-sdp-attention --opt-sub-quad-attention --opt-channelslast --precision autocast --no-half --device-id=0

set CUDA_MODULE_LOADING=LAZY
set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
call webui.bat

```

```
ERROR:root:Exporting to ONYX failed. Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

v0.1.0 was able to generate the ONYX, so I think I will try to fallback the version first.

**Comment by devildelta** [comment]
Also note that the checkpoint using is not SDXL, it should be based on SD1.5.

**Comment by ItsSkynet** [comment]
> After removing Unet folder contents and restarted the instance, when I tried to regenerate the default engine, the `Expected all tensors to be on the same device` occurs.
> 
> ```
> @echo off
> 
> set PYTHON=
> set GIT=
> set VENV_DIR=
> set COMMANDLINE_ARGS=--xformers --opt-sdp-attention --opt-sub-quad-attention --opt-channelslast --precision autocast --no-half --device-id=0
> 
> set CUDA_MODULE_LOADING=LAZY
> set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
> call webui.bat
> ```
> 
> ```
> ERROR:root:Exporting to ONYX failed. Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
> ```
> 
> v0.1.0 was able to generate the ONYX, so I think I will try to fallback the version first.

just aspeculation, but could it be that --device-id=0 is listing both the cpu and gpu? if so, then "Expected all tensors to be on the same device, but found at least two devices" would make sense.

**Comment by devildelta** [comment]
Somehow force update `xformers` from `0.0.20` to `0.0.23` and `torch` from `2.0.1+cu118` to `2.1.3+cu118` has fixed the issue, ONNX can be exported and TensorRT engine can be built.

**Comment by devildelta** [comment]
Nope, updating dependencies only resolved the rebuild issue, but same issue still occurs when

**Comment by maxxrox** [comment]
Hitting the same. Uncertain when it broke. Followed all the steps in this thread (inclusive of blowing away venv a couple times during testing).

ONNX/TRT that were generated prior to whatever broke continue to function as expected, inclusive of handling over 75 tokens (more on that below). I saved those off, then attempted to regenerate the ONNX/TRT models using the exact same input .safetensors and parameters, but continue to receive the same error if Max Tokens isn't 75.

If it's helpful: generating ONNX/TRT models without increasing the Max Tokens parameter appears to work (inclusive of Hires. fix, presuming final resolution is blow whatever maximum was set in the TRT options)  without throwing the initial `__len__() should return >= 0` error. Unfortunately, it means text inputs greater than 75 tokens are discarded and new errors are logged in the console:

`[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,154,768] for bindings[2] exceed min ~ max range at index 1, maximum dimension in profile is 77, minimum dimension in profile is 77, but supplied dimension is 154.`

**Comment by maxxrox** [comment]
Addendum, in case it's helpful:

Using the same generation values (single batch size, 256-1280 L+W max/min, 75/75/300 min/opt/max prompt size) for exact same model, results in different sample filenames before and after breaking-update:

**Working; generated before breaking change**
`[filename][hash]_sample=1x4x32x32+2x4x64x64+2x4x160x160-timesteps=1+2+2-encoder_hidden_states=1x77x768+2x77x768+2x308x768`

**Not working; generated after breaking change**
`[filename][hash]_sample=1x4x32x32+1x4x64x64+1x4x160x160-timesteps=1+1+1-encoder_hidden_states=1x77x768+1x77x768+1x308x768`

**Comment by devildelta** [comment]
Regenerated TRTs, no help. 


Profile selected:
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/9845381/f311df5f-80c5-48df-9763-2d3c0e6fd017)
```
Loaded Profile: 1
        sample = [(2, 4, 80, 40), (2, 4, 120, 64), (2, 4, 160, 80)]
        timesteps = [(2,), (2,), (2,)]
        encoder_hidden_states = [(2, 77, 768), (2, 77, 768), (2, 77, 768)]
        latent = [(-1945833728), (-1945834240), (-1945833216)]
```

`[filename]_[hash]_cc86_sample=2x4x80x40+2x4x120x64+2x4x160x80-timesteps=2+2+2-encoder_hidden_states=2x77x768+2x77x768+2x77x768`

I also observed the following error log also before it yields `__len__() should return >= 0`:
```
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,4,80,40] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 2, minimum dimension in profile is 2, but supplied dimension is 1.
```

**Comment by devildelta** [comment]
Another interesting observation is that, when I first launched `WebUI` and using default prompts without hires fix to generate, it works; when then I turned on hires fix, it fails; and then when I turned off hires fix and generate again, it fails again.

**Comment by devildelta** [comment]
I usually use `20` steps and when it works, the error of the `supplied dimension` appears when it is `>=15` steps. 
```
 75%|█████████████████████████████████████████████████████████████▌                    | 15/20 [00:01<00:00, 14.94it/s][E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,4,80,40] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 2, minimum dimension in profile is 2, but supplied dimension is 1.
    )
```

**Comment by devildelta** [comment]
BTW, when I recall the previous behavior that worked, I should have observed the generation process is actively switching between generated engines, when doing hires fix. This behavior was in `v0.1.0` and I am not able to observe this in `v0.2.0`.

**Comment by roselma** [comment]
This has happened twice for me, once after doing a force-rebuild of a profile, which erroneously resulted in two identical profiles (according to the list of profiles in the TensorRT tab) instead of replacing the existing one, and the second time after creating a dynamic profile whose resolution range overlapped with another.  The first time, I resolved it by removing my Unet-trt and Unet-onnx directories.  This time I have resolved it by simply removing mention of one of the two profiles from Unet-trt/model.json.

In short, it seems that the trigger for this bug is the existence of profiles that overlap in some specific way that I haven't determined.  (Maybe if one is a perfect subset of the other?)

To get a little bit more specific about the cause of the false assertion:
```python
            tensor = torch.empty(
                tuple(shape), dtype=numpy_to_torch_dtype_dict[dtype]
            ).to(device=device)
```
`shape` in this call is a `Dims` equal to `(0)`, which apparently returns a negative number when `len()` is called on it (which happens as a result of the `tuple()` conversion).

**Comment by roselma** [comment]
I added a `print` statement to show the value of `shape` for each iteration of the loop in `Engine.allocate_buffers` (utilities.py).

When there are overlapping profiles and the problem occurs:
```txt
shape 0=torch.Size([1, 4, 64, 96])
shape 1=torch.Size([1])
shape 2=torch.Size([1, 77, 768])
[E] 3: [executionContext.cpp::resolveSlots::2868] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::2868, condition: allInputDimensionsSpecified(routine)
    )
shape 3=(0)
```

When I pare down the model.json file to contain only one base profile and one dynamic profile for this checkpoint and the problem does not occur:
```txt
shape 0=torch.Size([1, 4, 64, 96])
shape 1=torch.Size([1])
shape 2=torch.Size([1, 77, 768])
shape 3=(1, 4, 64, 96)
```

**Comment by maxxrox** [comment]
> When I pare down the model.json file to contain only one base profile and one dynamic profile for this checkpoint and the problem does not occur:

This did not resolve for me when doing my initial testing; I removed the ONNX and TRT folders entirely and relaunched Automatic1111 to rebuild the empty .json and folder structure, then recreated ONNX/TRT files. Zero models, zero configs. 

Same errors occurred when I rebuilt models using known-good values that worked in previous versions of the extension.

Only fix in my case was to reduce min/opt/max tokens to 75. Highres. fix worked fine with batch 1/1/1:

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/abe01344-7b0c-4c15-9ff9-ead0e713d25d)

**Comment by roselma** [comment]
@maxxrox, this definitely seems like a regression, so things that worked before do not necessarily work now.  I suspect you will have no problem as long as you don't have more than one profile that _could_ apply to whatever resolution + batch size you're doing.  I can definitely create dynamic profiles that support multiple batch sizes.  Things only go sideways when I have two or more profiles for one checkpoint and, as far as I can tell, only when the resolution and batch size ranges overlap...perhaps in some specific way I don't know how to characterize, because _sometimes_ even that works.

**Comment by maxxrox** [comment]
Not certain that model overlap is the issue in my case. This configuration (the one, sole, single, solitary config I have) works to generate native resolution **_and_** Highres. fix'd images:
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/6f77b6b6-06e5-4ce1-9e45-e9886ff1e7f6)

I removed the Unet-TRT and Unet-ONNX folders entirely, then restarted Automatic1111. Here is confirmation that I have zero, zilch, nada, nil, (0) profiles available:
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/81ed6fd2-40a6-4a2e-ad5e-198ec75097d7)
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/99ed7677-ed1d-4c54-836c-fc93cdf99a78)

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/89781257-a269-4d4d-8086-c6a8da6fdb39)
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/a9a4552b-a572-4b6a-943c-a3ad1a166c83)


I then rebuild the exact same model as evidenced in screenshot 1 above, with the **_sole_** change being that the Text-Length parameter are set to 75/150/225 (instead of 75/75/75 in the above working model):
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/52d89150-0157-4842-9b6c-a10d35b7d50f)


Then run it (without Highres. fix enabled, 512x512 default resolution):
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/5b66066b-d3a1-4e3a-8729-08b1a0d3c9b0)


_Voila_. Errors.

Crazy bit is that I can restore the ONNX/TRT built in the previous version of this extension and it works fine with >75 tokens. I simply cannot recreate that _exact same model_ in v0.2.0.

**Comment by roselma** [comment]
It’d be interesting to recreate exactly the same profile that worked in the prior version and diff (1) the model.json files and (2) the lists of files in those two directories.On Jan 20, 2024, at 11:10, maxxrox ***@***.***> wrote:﻿
Not certain that model overlap is the issue in my case. This configuration (the one, sole, single, solitary config I have) works to generate native resolution and Highres. fix'd images:
image.png (view on web)
I removed the Unet-TRT and Unet-ONNX folders entirely, then restarted Automatic1111. Here is confirmation that I have zero, zilch, nada, nil, (0) profiles available:
image.png (view on web)
image.png (view on web)
image.png (view on web)
image.png (view on web)
I then rebuild the exact same model as evidenced in screenshot 1 above, with the sole change being that the Text-Length parameter are set to 75/150/225 (instead of 75/75/75 in the above working model):
image.png (view on web)
Then run it (without Highres. fix enabled, 512x512 default resolution):
image.png (view on web)
Voila. Errors.
Crazy bit is that I can restore the ONNX/TRT built in the previous version of this extension and it works fine with >75 tokens. I simply cannot recreate that exact same model in v0.2.0.

**Comment by maxxrox** [comment]
Uncertain is has anything to do with the model.json file itself; the model-creation process itself outputs different filenames (see above). Regardless, here you go; this is the comparison between my the model.json files corresponding to the two versions tested in Automatic1111 detailed in my post above.:

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/4ef0073b-7dd7-4978-9401-b70f5d2c6373)

Insofar as I can tell, the issue isn't in the models.json itself (it's simply recording what _**is**_), but rather the export process is specifying incorrect shapes at model creation. See my post above about filename differences/comparison of models exported in v0.2.0 and in the prior release.

**Comment by roselma** [comment]
I see what you mean, @maxxrox.

I tried to reproduce this by removing both of my Unet directories and creating a profile with the same settings as yours.  Oddly, when I do this, I encounter a _different_ issue: It reports that there are no suitable engines found.

**Comment by maxxrox** [comment]
I have some that works with optimal/max tokens greater than 75, but they were all generated prior to the v0.2.0 release. I haven't been successful in generating them since.

Also interesting re: highres. fix not working for some folks using a batch size less than 2; the only bit I've noticed is that the post-upscaled image size must be lower than or equal to the max size supported by the ONNX/TRT. E.g., I could only use x2 upscaling on a base 1024x1024 image if my max supported resolution is 2040x2048. Using 2.5 upscaling on a base 1024x1024 image would result in an error (honestly, would be better if a console warning were throne and the UNET disabled for the generation, but that's a separate enhancement request rather than a bug report).

**Comment by maxxrox** [comment]
> In the [readme file](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/e2b6980cba42243fd55022ac50d086550676abb6/README.md) said:
> 
> ```
> Resolution: When generating images, the resolution needs to be a multiple of 64. This applies to hires.fix as well, requiring the low and high-res to be divisible by 64.
> ```
> 
> I solved this problem by changing the resolution.

Thanks for weighing in, but this comment is not applicable. Please read the thread above. As you can see, this error occurs when using resolution 512x512:
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/7402208/321a1352-0fb4-4dc8-a9c9-3b621050131d)

**Comment by devildelta** [comment]
For the previously mentioned error
```
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,4,40,80] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 4, minimum dimension in profile is 2, but supplied dimension is 1.)
```

When I injected the print log suggested by @maxxrox , I see the following:

```
 75%|█████████████████████████████████████████████████████████████▌                    | 15/20 [00:01<00:00, 17.34it/s]
shape 0=torch.Size([1, 4, 40, 80])
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,4,40,80] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 4, minimum dimension in profile is 2, but supplied dimension is 1.
shape 1=torch.Size([1])
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1] for bindings[1] exceed min ~ max range at index 0, maximum dimension in profile is 4, minimum dimension in profile is 2, but supplied dimension is 1.
shape 2=torch.Size([1, 77, 768])
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2046, condition: profileMinDims.d[i] <= dimensions.d[i]. Supplied binding dimension [1,77,768] for bindings[2] exceed min ~ max range at index 0, maximum dimension in profile is 4, minimum dimension in profile is 2, but supplied dimension is 1.
```
It seems the batch_size in the shape suddenly changes from 2 to 1 at this step and I don't know why.

**Comment by devildelta** [comment]
This is due to `Negative Guidance minimum sigma` set.
The value I set was 0.33, so the last 33% of steps (~6.6 = 6) will skip negative prompt, and therefore reduced a dimension. 

Resetting value to zero eliminated the shape error.

**Comment by devildelta** [comment]
```
tensor(... ...)
shape 0=torch.Size([2, 4, 80, 40])

tensor([999., 999.], device='cuda:0')
shape 1=torch.Size([2])

tensor([[[-0.3787,  0.0214, -0.0475,  ..., -0.4611, -0.3003,  0.0575],
         [-1.0053, -0.3166,  2.1954,  ..., -0.5814,  0.8775, -0.7874],
         [-1.9166, -0.3008,  1.5344,  ...,  0.2911,  0.5383, -0.2709],
         ...,
         [ 1.2781, -0.5123,  0.1328,  ...,  0.4920, -2.1129, -0.7022],
         [ 1.2668, -0.5150,  0.1203,  ...,  0.4973, -2.1449, -0.7328],
         [ 1.1520, -0.5386,  0.1315,  ...,  0.6207, -2.3053, -0.8234]],

        [[-0.3943,  0.0223, -0.0495,  ..., -0.4802, -0.3128,  0.0599],
         [ 0.5520, -0.7075,  0.2375,  ..., -0.3554,  1.5901, -0.9215],
         [ 0.8309,  0.6456,  0.5782,  ..., -0.8517, -0.0687, -1.1418],
         ...,
         [ 0.5583,  0.2160, -0.9537,  ..., -0.5698, -0.1652, -1.4681],
         [ 0.5301,  0.2512, -0.8903,  ..., -0.6384, -0.1873, -1.4783],
         [ 0.6110,  0.3418, -0.9354,  ..., -0.6222, -0.1316, -1.4487]]],
       device='cuda:0')
shape 2=torch.Size([2, 77, 768])

shape 3=(-1945994997)

ValueError: __len__() should return >= 0
```

**Comment by Bassel6254** [comment]
Has anyone found a way to fix this? I'm also getting this error with multiple dynamic profiles.

**Comment by devildelta** [comment]
From latest attempts, it becomes working when
- using engine with batch size 2 or above; and
- disable `Negative Guidance minimum sigma`

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/9845381/899b0bb6-3ffa-46d2-884f-d95fdd8dec83)
