### ISSUE TITLE
Installation fails with permission issue on google\\~-pb\\_message.pyd

### ISSUE THREAD

**Issue by maciekish** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#232]
Installed a fresh sd-webui 1.7.0 and when trying to install this extension i get the error below on Windows x64. I am the admin and have tried taking ownership of the entire sd-webui folder and can open and save the _message.pyd file in notepad without elevating. However Python thinks otherwise...

```
*** Error running install.py for extension E:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT.
*** Command: "E:\stable-diffusion-webui\venv\Scripts\python.exe" "E:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py"
*** Error code: 1
*** stdout: Collecting protobuf==3.20.2
***   Using cached protobuf-3.20.2-cp310-cp310-win_amd64.whl (904 kB)
*** Installing collected packages: protobuf
***   Attempting uninstall: protobuf
***     Found existing installation: protobuf 4.23.4
***     Uninstalling protobuf-4.23.4:
***       Successfully uninstalled protobuf-4.23.4
*** GS is not installed! Installing...
*** Installing protobuf
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
***     WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'E:\\stable-diffusion-webui\\venv\\Lib\\site-packages\\google\\~-pb\\_message.pyd'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (e:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: You are using pip version 21.2.3; however, version 23.3.2 is available.
*** You should consider upgrading via the 'E:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip' command.
*** Traceback (most recent call last):
***   File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 67, in <module>
***     install()
***   File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 50, in install
***     launch.run_pip("install protobuf==3.20.2", "protobuf", live=True)
***   File "E:\stable-diffusion-webui\modules\launch_utils.py", line 144, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "E:\stable-diffusion-webui\modules\launch_utils.py", line 116, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install protobuf.
*** Command: "E:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install protobuf==3.20.2 --prefer-binary
*** Error code: 1
```

**Comment by pdavis68** [comment]
I'm got this as well, so I killed webui.

I ran the pip update command it suggested (\path_to_webui\venv\Scripts\python.exe -m pip install --upgrade pip).
Then I deleted the extension folder.
Then I re-ran webui-user.bat 

That seemed to get it working.
