### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#239]
A1111`s webui https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cb5b335acddd126d4f6c990982816c06beb0d6ae

```
*** Error executing callback ui_tabs_callback for D:\SDWebUI\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "D:\SDWebUI\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "D:\SDWebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 612, in on_ui_tabs
        choices=get_valid_lora_checkpoints(),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\SDWebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 290, in get_valid_lora_checkpoints
        available_lora_models = get_lora_checkpoints()
                                ^^^^^^^^^^^^^^^^^^^^^^
      File "D:\SDWebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 270, in get_lora_checkpoints
        config = json.load(f)
                 ^^^^^^^^^^^^
      File "C:\Users\gojas\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
                     ^^^^^^^^^
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe7 in position 188: illegal multibyte sequence
```

**Comment by Thisisashan** [comment]
Same issue I am having, though I also have

      File "C:\Users\thisi\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]

Right before the unicode decode error.

**Comment by DAYNEMOS** [comment]
same...

```
   File "C:\Users\tregu\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
```

**Comment by ricky469469** [comment]
Here is my solution of "cp950" error for Windows 11 by changing system language:

Go to language & region setting
Select Beta version
Reboot your PC
Run webUI

It works for me. Maybe it works for other "cpxxx" error.

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/70641747/826c08d3-7e28-45a8-8941-e09df9a68a2f)

**Comment by rltgjqmcpgjadyd** [comment]
wow it`s work! 
thx!

**Comment by Yomisana** [comment]
> Here is my solution of "cp950" error for Windows 11 by changing system language:
> 
> Go to language & region setting Select Beta version Reboot your PC Run webUI
> 
> It works for me. Maybe it works for other "cpxxx" error.
> 
> ![image](https://private-user-images.githubusercontent.com/70641747/316511257-826c08d3-7e28-45a8-8941-e09df9a68a2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MjgwMzcsIm5iZiI6MTcxMTcyNzczNywicGF0aCI6Ii83MDY0MTc0Ny8zMTY1MTEyNTctODI2YzA4ZDMtN2UyOC00NWE4LTg5NDEtZTA5ZGY5YTY4YTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE1NTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDA1YmRlYjRkYWUwMmZjMDZmMzMxNWIyNzhiYTU2ZjUxMTE0NDU5NmMyZDNkNmY4ZDI2MTc0NTJiNzRjNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZcBydAOjvtYIir7tOyydGVPtVWcKKVT3DdA0_R41AW0)

Hi there, my issue #297 seems have indirectly fixed, you can try it in my fork repo.
May try on my repo if it fixed.
So... won't need to change this operation system settings stuff

**Comment by Xiony** [comment]
Hello, here is a fix suggested by Deepseek, which worked for me:

open **ui_trt.py**
Replace the line **269** :
`with open(config_file, "r") as f:`
By :
`with open(config_file, "r", encoding="utf-8") as f:`

**Comment by a-cidm** [comment]
This issue is addressed in PR #353 .
The fix enforces UTF-8 encoding when reading JSON files to avoid UnicodeDecodeError.
