### ISSUE TITLE
False "No model available for both LOWRES and HIRES"

### ISSUE THREAD

**Issue by roselma** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#244]
Extension version info:
```
commit e2b6980cba42243fd55022ac50d086550676abb6 (HEAD -> main, tag: v0.2.0, origin/main, origin/HEAD)
```

I have generated a base profile (512x512, too low-resolution to be used at all in my generations) and a dynamic profile for hires fix for one model.

```
Available TensorRT Engine Profiles
my_checkpoint (3 Profiles)
Profile 0
        Min     Opt     Max
Height  512     512     768
Width   512     512     768
Batch Size      1       1       4
Text-length     75      75      150
Profile 1
        Min     Opt     Max
Height  256     1536    1536
Width   256     1536    1536
Batch Size      1       1       1
Text-length     75      75      150
Profile 2
        Min     Opt     Max
Height  256     1536    1536
Width   256     1536    1536
Batch Size      1       1       1
Text-length     75      75      150
```

(Note that the identical profiles did not appear until I tried a "force rebuild" to circumvent this issue.  That's a separate issue, for which I will also file a report.  This issue happened before the forced rebuild as well.)

When the corresponding unet is enabled, base generations at 768x768 use the profile.  When I enable 2x hires fix, I receive these messages:
```
warning
Enabling PyTorch fallback as no engine was found.
warning
No model available for both (my_checkpoint) LOWRES (768x768) and HIRES (1536x1536). This will slow-down inference.
```

No messages appear in the console when this happens.

If I revert to v0.1.0, I simply see an exception in the console instead.
```
    ValueError: No valid profile found. Please go to the TensorRT tab and generate an engine with the necessary profile. If using hires.fix, you need an engine for both the base and upscaled resolutions. Otherwise, use the default (torch) U-Net.
```

Prior to "upgrading" to v0.2.0, I did not have this problem.  It may have begun after I upgraded to  v0.2.0 because I had to remove my `Unet-trt` and `Unet-onnx` directories from the models directory because there was something in there that the new version could not cope with.

**Comment by roselma** [comment]
The following seems highly relevant.  `TensorRTScript.get_profile_idx` thinks the last argument to `ModelManager.get_valid_models` is a `model_type`.  `ModelManager.get_valid_models` (and `ModelConfig.is_compatible`, which it calls) beg to differ.

```
    def get_profile_idx(self, p, model_name: str, model_type: ModelType) -> (int, int):
...
        ) = modelmanager.get_valid_models(
            model_name,
            p.width,
            p.height,
            p.batch_size,
            77,  # model_type
        )  # TODO: max_embedding, just ignore?
...
            valid_models_hr, distances_hr, idx_hr = modelmanager.get_valid_models(
                model_name,
                hr_w,
                hr_h,
                p.batch_size,
                77,  # model_type
            )  # TODO: max_embedding

```

```
    def get_valid_models(
        self,
        base_model: str,
        width: int,
        height: int,
        batch_size: int,
        max_embedding: int,
    ):
        valid_models = []
...
```

```
    def is_compatible(
        self, width: int, height: int, batch_size: int, max_embedding: int
    ):
        distance = 0
        sample = self.profile["sample"]
        embedding = self.profile["encoder_hidden_states"]

        batch_size *= 2
        width = width // 8
        height = height // 8

        _min, _opt, _max = sample
        if _min[0] > batch_size or _max[0] < batch_size:
            return (False, distance)
        if _min[2] > height or _max[2] < height:
            return (False, distance)
        if _min[3] > width or _max[3] < width:
            return (False, distance)

        _min_em, _opt_em, _max_em = embedding
        if _min_em[1] > max_embedding or _max_em[1] < max_embedding:
            return (False, distance)

        distance = (
            abs(_opt[0] - batch_size)
            + abs(_opt[2] - height)
            + abs(_opt[3] - width)
            + 0.5 * (abs(_max[2] - height) + abs(_max[3] - width))
        )

        return (True, distance)
```

**Comment by roselma** [comment]
So... "False" in the title of this issue might be a misnomer.  I added some debug print statements in `ModelConfig.is_compatible` and discovered that it is not the wrong-_looking_ business with `model_type` vs `max_embedding`; it's batch size.  I made my profile have maximum batch size of one because that is the batch size that I am using; however, I can see that when I attempt a generation with hires fix, the batch size given in the `modules.processing.StableDiffusionProcessingTxt2Img` object is two.

Creating a profile with a maximum batch size of two eliminates _this_ problem... and reveals another.

```
  0%|                                                                                                                                                                                                      | 0/20 [00:00<?, ?it/s][E] 3: [executionContext.cpp::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,4,96,96] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2] for bindings[1] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,77,768] for bindings[2] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::resolveSlots::2868] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::resolveSlots::2868, condition: allInputDimensionsSpecified(routine)
    )
  0%|                                                                                                                                                                                                      | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(08qfcvqhlj9yxfu)', 'lame', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 768, 768, True, 0.7, 2, 'Lanczos', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x7f0b5e3b41f0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, 1, 0, False, 1, 0, 4, 512, 512, True, 'None', 'None', 0, 1, '', 0, '', True, False, False, False, '', 1, True, 100, False, False, 'positive', 'comma', 0, False, False, 'start', '', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "/home/m/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/home/m/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/home/m/stable-diffusion-webui/modules/processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "/home/m/stable-diffusion-webui/modules/processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/home/m/stable-diffusion-webui/modules/processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/home/m/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/m/stable-diffusion-webui/modules/sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "/home/m/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/m/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/home/m/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "/home/m/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/home/m/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/home/m/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/home/m/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/home/m/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/m/stable-diffusion-webui/modules/sd_unet.py", line 89, in UNetModel_forward
        return current_unet.forward(x, timesteps, context, *args, **kwargs)
      File "/home/m/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/scripts/trt.py", line 70, in forward
        self.engine.allocate_buffers(feed_dict)
      File "/home/m/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/utilities.py", line 304, in allocate_buffers
        tuple(shape), dtype=numpy_to_torch_dtype_dict[dtype]
    ValueError: __len__() should return >= 0

---
```

**Comment by roselma** [comment]
Given that I still don't have it working, maybe I am jumping to a conclusion, but it seems like you should probably document the fact that a minimum of 2 for the maximum profile batch size is required to use TRT with hires fix.

**Comment by roselma** [comment]
After removing all my profiles (again), I no longer receive the error [above](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/244#issuecomment-1891084827).

**Comment by roselma** [comment]
Apparently related:

In `export_unet_to_trt`:
```
    profile = modelobj.get_input_profile(profile_settings)
```
In `get_input_profile`:
```
    min_batch, opt_batch, max_batch = profile.get_a1111_batch_dim()
```
`get_a1111_batch_dim`:
```
    def get_a1111_batch_dim(self):
        static_batch = self.bs_min == self.bs_max == self.bs_opt
        if self.t_max <= 77:
            return (self.bs_min * 2, self.bs_opt * 2, self.bs_max * 2)
        elif self.t_max > 77 and static_batch:
            return (self.bs_opt, self.bs_opt, self.bs_opt)
        elif self.t_max > 77 and not static_batch:
            if self.t_opt > 77:
                return (self.bs_min, self.bs_opt, self.bs_max * 2)
            return (self.bs_min, self.bs_opt * 2, self.bs_max * 2)
        else:
            raise Exception("Uncovered case in get_batch_dim")
```

So under certain circumstances—when max tokens is not more than 75—the batch size parameters are all doubled, which seems like it must be why `is_compatible` doubles the requested batch size, but it does so unconditionally, which seems to be the crux of the issue...maybe?

**Comment by maxxrox** [comment]
def get_a1111_batch_dim(self): _# define the method_
        static_batch = self.bs_min == self.bs_max == self.bs_opt _# sets the static_batch flag if min/max/opt tokens are all equal, which is incorrect, I think? Static batch flag should be set on the condition that  **_dimension_** min/max/opt are equal rather than batchsize._
        if self.t_max <= 77:
            return (self.bs_min * 2, self.bs_opt * 2, self.bs_max * 2) _# looks like this doubles the batchsize params, as you say_
        elif self.t_max > 77 and static_batch: _# this is where the logic escapes me; this bit says "if max tokensize is greater than 77 (75+2 padded-use, normal) **and** tokensize min/max/opt are all equal" (see method comments above), then return the params from the line directly below._
            return (self.bs_opt, self.bs_opt, self.bs_opt)
        elif self.t_max > 77 and not static_batch: _# Translation: max tokens is greater than 75 (in UI) and the min/max/opt tokens are not the same, return the same value as the first method above._
            if self.t_opt > 77:
                return (self.bs_min, self.bs_opt, self.bs_max * 2)
            return (self.bs_min, self.bs_opt * 2, self.bs_max * 2)
        else:
            raise Exception("Uncovered case in get_batch_dim")

I haven't parsed through the .py files to see what feeds/is fed by this snippet, but the logic looks off, as it's interpreting token options as batch sizes.
