### ISSUE TITLE
ModuleNotFoundError: No module named 'optimum'

### ISSUE THREAD

**Issue by BlankFX1** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#258]
Since I updated to v0.2.0 I get this error at startup, leading to no TensorRT Tab being availabile in the WebUI.
```
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "B:\stable-diffusion-automatic1111\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "B:\stable-diffusion-automatic1111\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "B:\stable-diffusion-automatic1111\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 13, in <module>
        import ui_trt
      File "B:\stable-diffusion-automatic1111\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 18, in <module>
        from exporter import export_onnx, export_trt, export_lora
      File "B:\stable-diffusion-automatic1111\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 15, in <module>
        from optimum.onnx.utils import (
    ModuleNotFoundError: No module named 'optimum'
```

Reverting back to v0.1.0 fixed the issue.

**Comment by kuska128** [comment]
> Simplest fix would be to just go into the webUI directory, activate the venv and just `pip install optimum`, After that look for any other missing stuff inside the CMD. Might be that your internet skipped a beat when downloading some stuff.
> 
> I wouldn't however update to v0.2.0. There's a LOT of issues making it unstable and in some cases not usable.

please help, my stable diffusion webUI was working last time i used it , and when i launch it today, i got the same error, i ran the  pip install optmum and it makes no difference, did it install somewhere else? or update something? how tor revert? im new and i don't know coding, im just going off intuition on what those codes mean.

**Comment by 78Alpha** [comment]
You would need to activate the venv in order to install.

As a general, from what I have found, the new TensorRT simply doesn't install any of the requirements.
