### ISSUE TITLE
Error message:  AttributeError: 'NoneType' object has no attribute 'profile_idx'

### ISSUE THREAD

**Issue by BronxBob** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#275]
I get this error when generating images. It just seems to take longer but nothing else bad happens. This happens when I do single and batch images. I do see weird hands sometimes not sure if this is related. 

*** Error running process_batch: X:\SDXL_A111\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "X:\SDXL_A111\stable-diffusion-webui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "X:\SDXL_A111\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 302, in process_batch
        if self.idx != sd_unet.current_unet.profile_idx:
    AttributeError: 'NoneType' object has no attribute 'profile_idx'

**Comment by BronxBob** [comment]
I believe this in the same or similar issue
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/250

How do I create a profile in TensorRT? Is this referring to my posting profile here? (I know that makes no sense... only thing that pops into my head at the moment..MORE GOOGLING!!)

**Comment by dislive** [comment]
same problem

**Comment by BronxBob** [comment]
Here is the answer I was sent (by [LarsiboyCGN](https://github.com/LarsiboyCGN) :
> In the Extension there is a Button named "Generate default Engines" .. [watch on youtube](https://youtu.be/ssPhVOgd1Qc?si=6POjgkCkoKWY_2hN&t=927)
