### ISSUE TITLE
after install tensorRT, loading with this error。。。json.decoder.JSONDecodeError: Expecting value: line 2875 column 36 (char 193761)

### ISSUE THREAD

**Issue by jasoncow007** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#304]
loading settings: JSONDecodeError
Traceback (most recent call last):
  File "D:\sd-webui_forge\webui\modules\ui_loadsave.py", line 29, in __init__
    self.ui_settings = self.read_from_file()
  File "D:\sd-webui_forge\webui\modules\ui_loadsave.py", line 141, in read_from_file
    return json.load(file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2875 column 36 (char 193761)

**Comment by shodanx2** [comment]
Hi,

Not sure if related, 

but I'm seeing the following error message from running webui-user.sh

```
*** Error executing callback ui_tabs_callback for /opt/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/scripts/trt.py
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "/opt/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/ui_trt.py", line 615, in on_ui_tabs
        choices=get_valid_lora_checkpoints(),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/ui_trt.py", line 293, in get_valid_lora_checkpoints
        available_lora_models = get_lora_checkpoints()
                                ^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/ui_trt.py", line 270, in get_lora_checkpoints
        config = json.load(f)
                 ^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 293, in load
        return loads(fp.read(),
               ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

---
```


However it still works  for me

**Comment by shodanx2** [comment]
Here are some more errors I spotted while generating.

It otherwise generated successfully, the messages may be spurious ?

```
reading extra network user metadata from /opt/stable-diffusion-webui/models/Lora/Zdzislaw_Beksinski_ArtStyle_selected.json: JSONDecodeError
Traceback (most recent call last):
  File "/opt/stable-diffusion-webui/modules/extra_networks.py", line 221, in get_user_metadata
    metadata = json.load(file)
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
reading extra network user metadata from /opt/stable-diffusion-webui/models/Lora/Zdzislaw_Beksinski_ArtStyle_selected.json: JSONDecodeError
Traceback (most recent call last):
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/stable-diffusion-webui/modules/extra_networks.py", line 221, in get_user_metadata
    metadata = json.load(file)
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
