### ISSUE TITLE
Error loading script: trt.py

### ISSUE THREAD

**Issue by Wolfinsteeeen** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#31]
After installing the TensorRT extension this appears before the ui launches. The TensorRT extension does appear in the extensions tab but it doesn't appear in the UI itself.

** Error loading script: trt.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 10, in <module>
        import ui_trt
      File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 16, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 219, in <module>
        modelmanager = ModelManager()
      File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 35, in __init__
        self.update()
      File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 67, in update
        for base_model, models in base_models.items():
    RuntimeError: dictionary changed size during iteration

---
Exception ignored in: <function ModelManager.__del__ at 0x0000021A6579CDC0>
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 87, in __del__
    self.update()
  File "F:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 67, in update
    for base_model, models in base_models.items():
RuntimeError: dictionary changed size during iteration

**Comment by contentis** [comment]
This is fixed in #43 and will be merged into the main branch soon.
