### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_bindings'

### ISSUE THREAD

**Issue by fernandoyang83** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#41]
Hello,

I've follow the instructions to install the TensorRT extension. But I've encountered 3 problem:

1. I've not found the Generate Default Engine Button described in the README.md
2. After installation, when I start up the webui, I get these erro messages:
```
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "C:\Users\ferna\SD\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ferna\SD\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\ferna\SD\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 10, in <module>
        import ui_trt
      File "C:\Users\ferna\SD\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 10, in <module>
        from exporter import export_onnx, export_trt
      File "C:\Users\ferna\SD\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 10, in <module>
        from utilities import Engine
      File "C:\Users\ferna\SD\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 32, in <module>
        import tensorrt as trt
      File "C:\Users\ferna\SD\venv\Lib\site-packages\tensorrt\__init__.py", line 18, in <module>
        from tensorrt_bindings import *
    ModuleNotFoundError: No module named 'tensorrt_bindings'
```
3. No models under SD Unet.

Much appreciated if someone can help me.

**Comment by fernandoyang83** [comment]
> Please follow this guide to resolve manually: [#27 (comment)](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566) A fix for this will be posted soon.

Thank you very much, it worked

**Comment by contentis** [comment]
Closing duplicates.
