### ISSUE TITLE
  RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by FurkanGozukara** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#42]
This happens when you have model in config file but later deleted model from Unet-trt folder

```
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "G:\auto_quick\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\auto_quick\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 10, in <module>
        import ui_trt
      File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 16, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 219, in <module>
        modelmanager = ModelManager()
      File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 35, in __init__
        self.update()
      File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 67, in update
        for base_model, models in base_models.items():
    RuntimeError: dictionary changed size during iteration

---
Exception ignored in: <function ModelManager.__del__ at 0x000001799BA029E0>
Traceback (most recent call last):
  File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 87, in __del__
    self.update()
  File "G:\auto_quick\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 67, in update
    for base_model, models in base_models.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by Wolfinsteeeen** [comment]
This happened to me as well. The extension worked the first time but when i tried to reinstall it this is the issue that kept appearing each time i launch stable diffusion

**Comment by FurkanGozukara** [comment]
i found my error. it was about missing tensor rt from config mismatch file naming

i fixed myself

**Comment by FurkanGozukara** [comment]
> I found the issue causing this. I added a fix for this in `hot_fix` branch.

actually i just did a pull request haha

https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/44
