### ISSUE TITLE
what is the problem of this ,(Error executing callback ui_tabs_callback)?????????

### ISSUE THREAD

**Issue by ironmanronmark** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#58]
Loading weights [e1441589a6] from Y:\Sd-UI-1.6\models\Stable-diffusion\v1-5-pruned.ckpt
*** Error executing callback ui_tabs_callback for Y:\Sd-UI-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "Y:\Sd-UI-1.6\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "Y:\Sd-UI-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 789, in on_ui_tabs
        choices=get_valid_lora_checkpoints(),
      File "Y:\Sd-UI-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 573, in get_valid_lora_checkpoints
        available_lora_models = get_lora_checkpoints()
      File "Y:\Sd-UI-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 561, in get_lora_checkpoints
        metadata = sd_models.read_metadata_from_safetensors(filename)
      File "Y:\Sd-UI-1.6\modules\sd_models.py", line 271, in read_metadata_from_safetensors
        json_obj = json.loads(json_data)
      File "Y:\Sd-UI-1.6\python\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "Y:\Sd-UI-1.6\python\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "Y:\Sd-UI-1.6\python\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1472 (char 1471)

**Comment by Bananamax** [comment]
Ah yes the callback error for the TensorRT. I have the same problem even after redownloading/reinstalling. TensorRT is just not working.

**Comment by jasoncow007** [comment]
I got this too,,,,how to uninstall it(delete the extention doesn;t work),, how to clear it and reinstall
