### ISSUE TITLE
ERROR:root:Could not allocate bytes object!

### ISSUE THREAD

**Issue by KoyuKansou** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#69]
ERROR:root:Could not allocate bytes object!
MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Funnystuff\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 84, in export_onnx
    torch.onnx.export(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\torch\onnx\utils.py", line 1587, in _export
    ) = graph._export_onnx(  # type: ignore[attr-defined]
RuntimeError: Could not allocate bytes object!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Funnystuff\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Funnystuff\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 154, in export_unet_to_trt
    export_onnx(
  File "C:\Funnystuff\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "_sitebuiltins.py", line 26, in __call__
SystemExit: None

Any fixes to the issue ?, i got this when i try to export the default engine

**Comment by contentis** [comment]
This sounds like torch is running out of system memory. How much RAM do you have installed in your system? Can you retry with as few apps running as possible?

**Comment by KoyuKansou** [comment]
> This sounds like torch is running out of system memory. How much RAM do you have installed in your system? Can you retry with as few apps running as possible?

i have 16gb ddr5 and tried to run SD only, still had the same issue

**Comment by contentis** [comment]
Can you open task manager and monitor the memory use? At this point, this is my best guess..

**Comment by KoyuKansou** [comment]
> Can you open task manager and monitor the memory use? At this point, this is my best guess..

yea... it exceeded 95% for a bit and then drop down
but now it crash instead
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/127967206/d064b810-6fa5-4160-afc3-e6c1026046c1)

**Comment by JTM2k** [comment]
yeah i have the same issue, 32GB DDR4 8GB VRAM,

for some reason after creating for than 1 engine with "Export to TRT" python just wanted 25GB RAM allocated, after killing the "python.exe" which alone had 10GB of the RAM, restarting the webui and it worked

**Comment by KoyuKansou** [comment]
so wondering if there's anyway to hard reduce the ram usage with the draw back of slower engine building?

**Comment by contentis** [comment]
You could try setting `diable_optimizations = True` to reduce the VRAM consumption here: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/exporter.py#L99

**Comment by KoyuKansou** [comment]
> You could try setting `diable_optimizations = True` to reduce the VRAM consumption here: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/exporter.py#L99

<img width="861" alt="image" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/127967206/2c3e6571-e518-496c-b2f4-a373b6ac1047">
huh?

**Comment by contentis** [comment]
Do not modify the if statement and just add a line above it as shown here: 
```
diable_optimizations = True
if diable_optimizations:
 .....
```

**Comment by KoyuKansou** [comment]
> Do not modify the if statement and just add a line above it as shown here:
> 
> ```
> diable_optimizations = True
> if diable_optimizations:
>  .....
> ```

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/127967206/f1826164-6da4-4090-ba70-ed304155998a)
well thank you it actually work now~
is it possible to document this just in case someone gets the same issue?

**Comment by contentis** [comment]
There is a chance this breaks things down the line when using LoRA. I'd need to test that first before recommending it.

If this doesn't break functionality, I could ad an "lowram" option in the UI.

**Comment by Foul-Tarnished** [comment]
16gb vram and 16gb ram, ram was the issue

simply adding 32gb of pagefile fixed the issue though
