### ISSUE TITLE
Error when use with controlnet SoftEdge model, preprocessor softedge_hed

### ISSUE THREAD

**Issue by emperor1412** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#70]
I've successfully build and run it with engine built for resolution 512x512.
But it doesn't work with controlnet yet, here is the error when I'm trying to use it with controlnet:

SD model: dreamshaper_8.safetensors [879db523c3]
Controlnet Model: control_v11p_sd15_softedge [a8575a2a]
Preprocessor: softedge_hed

`2023-10-19 16:30:20,360 - ControlNet - INFO - Preview Resolution = 512
2023-10-19 16:30:26,684 - ControlNet - INFO - Loading model: control_v11p_sd15_softedge [a8575a2a]
2023-10-19 16:30:29,608 - ControlNet - INFO - Loaded state_dict from [F:\stable-diffusion-webui\stable-diffusion-webui-practice\models\ControlNet\control_v11p_sd15_softedge.pth]
2023-10-19 16:30:29,609 - ControlNet - INFO - controlnet_default_config
2023-10-19 16:30:31,759 - ControlNet - INFO - ControlNet model control_v11p_sd15_softedge [a8575a2a] loaded.
2023-10-19 16:30:31,854 - ControlNet - INFO - Loading preprocessor: hed
2023-10-19 16:30:31,855 - ControlNet - INFO - preprocessor resolution = 512
2023-10-19 16:30:32,212 - ControlNet - INFO - ControlNet Hooked - Time = 5.776000738143921
  0%|                                                                                                                                    | 0/40 [00:01<?, ?it/s]
*** Error completing request
*** Arguments: ('task(yext2jd8oma0ppw)', '(absurdres, masterpiece, best quality, high quality, highres, ultra-detailed),', 'nsfw, nude, nipple, penis, noise, low res, blur, burry, worst quality, lowres, hermaphrodite, cropped, not in the frame, additional faces, jpeg large artifacts, jpeg small artifacts, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs,', [], 40, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000272318080A0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178C5E0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178E320>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178C370>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000027045C36E60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178DAE0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178DA20>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178FBE0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000272317D8130>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000272317DB220>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002723178FA60>, 'from modules.processing import process_images\n\np.width = 768\np.height = 768\np.batch_size = 2\np.steps = 10\n\nreturn process_images(p)', 2, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\processing.py", line 869, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions\sd-webui-controlnet\scripts\hook.py", line 451, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\processing.py", line 1145, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions\sd-webui-controlnet\scripts\hook.py", line 858, in forward_webui
        raise e
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions\sd-webui-controlnet\scripts\hook.py", line 855, in forward_webui
        return forward(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions\sd-webui-controlnet\scripts\hook.py", line 753, in forward
        emb = self.time_embed(t_emb)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\extensions-builtin\Lora\networks.py", line 472, in network_Linear_forward
        return originals.Linear_forward(self, input)
      File "F:\stable-diffusion-webui\stable-diffusion-webui-practice\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)`

**Comment by contentis** [comment]
ControlNet is currently not supported. See #71 for more information on this.
