### ISSUE TITLE
ERROR:root:Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

### ISSUE THREAD

**Issue by hanshaoUi** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#73]
To create a public link, set `share=True` in `launch()`.
Startup time: 44.7s (prepare environment: 12.0s, import torch: 6.8s, import gradio: 1.4s, setup paths: 0.9s, initialize shared: 0.5s, other imports: 0.8s, setup codeformer: 0.2s, load scripts: 6.1s, create ui: 14.5s, gradio launch: 1.3s, app_started_callback: 0.1s).
Exporting SDXL_sd_xl_base_1.0 to TensorRT
{'sample': [(1, 4, 96, 96), (2, 4, 128, 128), (8, 4, 128, 128)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 2048), (2, 77, 2048), (8, 154, 2048)], 'y': [(1, 2816), (2, 2816), (8, 2816)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ERROR:root:Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
Traceback (most recent call last):
  File "H:\GitHub\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 84, in export_onnx
    torch.onnx.export(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\onnx\utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\onnx\utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\onnx\utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\jit\_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\repositories\generative-models\sgm\modules\diffusionmodules\openaimodel.py", line 984, in forward
    emb = self.time_embed(t_emb)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\extensions-builtin\Lora\networks.py", line 429, in network_Linear_forward
    return originals.Linear_forward(self, input)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "H:\GitHub\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "H:\GitHub\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "H:\GitHub\sd-webui-aki-v4.4\python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by contentis** [comment]
SDXL is currently only supported in the Dev branch of Auto1111. Please see the readme: 
```Native SDXL support coming in a future release. Please use the [dev branch](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/dev) if you would like to use it today. Note that the Dev branch is not intended for production work and may break other things that you are currently using.```

**Comment by arafatx** [comment]
The same error occurs when configuring TensorRT.

@contentis I don't understand your post. Are you saying that the error is due to not being on the Dev branch, or are you suggesting that switching to the Dev branch would resolve the issue? Also how is SDXL related to this error ?
