### ISSUE TITLE
Error building engine

### ISSUE THREAD

**Issue by michael-imbeault** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#9]
Building TensorRT engine for C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\models\Unet-onnx\realismEngineSDXL_v10_af771c3f.onnx: C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\models\Unet-trt\realismEngineSDXL_v10_af771c3f_cc86_sample=2x4x128x128-timesteps=2-encoder_hidden_states=2x77x2048-y=2x2816.trt
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=2048093.89 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] Loading tactic timing cache from C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[E] 1: [myelinCache.cpp::nvinfer1::builder::MyelinAutotunerCache::deserialize::62] Error Code 1: Myelin (Myelin error from unknown graph)
[E] 4: The timing cache will not be used!
[I] Building engine with configuration:
    Flags                  | [FP16, REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 24575.50 MiB, TACTIC_DRAM: 24575.50 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
Building engine: 100%|##########| 6/6 [03:51<00:00, 38.63s/it]
[I] Finished engine building in 233.852 seconds
[E] 1: [myelinCache.cpp::nvinfer1::builder::MyelinAutotunerCache::deserialize::62] Error Code 1: Myelin (Myelin error from unknown graph)
[E] 4: The timing cache will not be used!
[I] Saving tactic timing cache to C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Saving engine to C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\models\Unet-trt\realismEngineSDXL_v10_af771c3f_cc86_sample=2x4x128x128-timesteps=2-encoder_hidden_states=2x77x2048-y=2x2816.trt
*** API error: POST: http://127.0.0.1:7860/api/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
    Traceback (most recent call last):
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
        await self.app(scope, receive, _send)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
        await response(scope, receive, send)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
        async with anyio.create_task_group() as task_group:
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
        raise exceptions[0]
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
        await func()
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
        return await super().stream_response(send)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
        await send(
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
'AsyncRequest' object has no attribute '_json_response_data'
        await send(message)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
        output = self.conn.send(event=response)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 468, in send
        data_list = self.send_with_data_passthrough(event)
      File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
        raise LocalProtocolError("Can't send data when our state is ERROR")
    h11._util.LocalProtocolError: Can't send data when our state is ERROR

---
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 255, in stream_response
    await send(
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 490, in send
    output = self.conn.send(event=response)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR

Then stalls, have to reboot UI

**Comment by michael-imbeault** [comment]
Closing, SDXL not yet supported

**Comment by michael-imbeault** [comment]
Tried again on a fully fresh install of A1111, no other extensions than tensor RT - same issue trying to build the default engine

**Comment by michael-imbeault** [comment]
Can confirm it is somehow related to https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/10 and the fix proposed there works (changing yield logging_history to print(logging_history)

**Comment by Adzido** [comment]
I have same problem on my OLD SD. Without addons also.

Any idea how to fix it? I have this error

Fresh SD working very well and I dont have error but I want to my loras, plugins etc...

**Comment by prusswan** [comment]
Having this issue, python 3.10.11 if it matters

**Comment by contentis** [comment]
As `yield` seems to be causing issues for some users it will be replaced by print and gr.Info. The changes are live on the `hot_fix` branch right now. 
Currently, I don't have an ETA when this branch will be merged into the master but hopefully by end of this week latest.

**Comment by Adzido** [comment]
> same issues here, i just git checkout the extension to hotfix branch and restart, the problem solved. (didn't install my webui)

How to intall hotfix? I have to delete and install again tensorrt exh? Or what?

**Comment by contentis** [comment]
FYI hot_fix has been merged now.
