### ISSUE TITLE
ERROR:root: Traceback (most recent call last):

### ISSUE THREAD

**Issue by 907739769** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#91]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --medvram-sdxl --theme dark --xformers --api --autolaunch
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
2023-10-20 13:39:47,337 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: E:\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\annotator\downloads
2023-10-20 13:39:47,480 - ControlNet - INFO - ControlNet v1.1.411
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [ca5befc099] from E:\sd-webui-aki-v4.4\models\Stable-diffusion\perfectWorld_v6Baked.safetensors
Running on local URL:  http://127.0.0.1:7860
Creating model from config: E:\sd-webui-aki-v4.4\configs\v1-inference.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 18.0s (prepare environment: 4.4s, import torch: 4.2s, import gradio: 1.6s, setup paths: 0.7s, initialize shared: 0.3s, other imports: 0.8s, setup codeformer: 0.1s, load scripts: 4.0s, create ui: 0.9s, gradio launch: 0.7s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: E:\sd-webui-aki-v4.4\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 8.8s (load weights from disk: 1.3s, create model: 0.4s, apply weights to model: 6.4s, load VAE: 0.2s, calculate empty prompt: 0.2s).
Exporting perfectWorld_v6Baked to TensorRT
{'sample': [(1, 4, 96, 64), (1, 4, 96, 64), (1, 4, 96, 64)], 'timesteps': [(1,), (1,), (1,)], 'encoder_hidden_states': [(1, 154, 768), (1, 154, 768), (1, 154, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
ERROR:root:
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 74, in export_onnx
    inputs = modelobj.get_sample_input(
  File "E:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 977, in get_sample_input
    latent_height, latent_width = self.check_dims(
  File "E:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 259, in check_dims
    assert batch_size >= self.min_batch and batch_size <= self.max_batch
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "E:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "E:\sd-webui-aki-v4.4\python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by 907739769** [comment]
first exopse default

**Comment by Blackdragon3035** [comment]
Hello, I have a similar problem. (Generation works only if you select Preset "Batch Size * (Static)"
PC characteristics
I3 10400F    32 GB DDR5   RTX 3070
Launching Web UI with arguments: --autolaunch --update-check --theme=dark --medvram-sdxl --xformers

Exporting babes_20 to TensorRT
{'sample': [(2, 4, 128, 128), (2, 4, 128, 128), (8, 4, 128, 128)], 'timesteps': [(2,), (2,), (8,)], 'encoder_hidden_states': [(2, 77, 768), (2, 77, 768), (8, 77, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
ERROR:root:
Traceback (most recent call last):
  File "E:\Stable Diffusion\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 74, in export_onnx
    inputs = modelobj.get_sample_input(
  File "E:\Stable Diffusion\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 977, in get_sample_input
    latent_height, latent_width = self.check_dims(
  File "E:\Stable Diffusion\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 263, in check_dims
    assert (
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Stable Diffusion\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Stable Diffusion\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "E:\Stable Diffusion\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "C:\Users\black\AppData\Local\Programs\Python\Python310\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

I will be glad for any help.
