### ISSUE TITLE
No ONNX file found. Exporting ONNX... Please check the progress in the terminal.

### ISSUE THREAD

**Issue by lingtingfengyu** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#96]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "D:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "D:\sd-webui-aki-v4.4\python\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by MorrisLu-Taipei** [comment]
, after checked, 
Magic, gradio upgrade to gradio: 3.41.0 . IT WORKS NOW.

**Comment by west1778** [comment]
> , after checked, Magic, gradio upgrade to gradio: 3.41.0 . IT WORKS NOW.

What do you mean by this I'm getting the same error? Do you mean you upgraded your Gradio?

**Comment by MorrisLu-Taipei** [comment]
<img width="936" alt="image" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/22585297/534eeddf-49e3-4f18-9dea-48f3e78e9d0b">
yes upgrade gradio the issue gone

**Comment by tetsuoo-online** [comment]
As you can see here I have Gradio 3.41.0 and still getting the same error. So maybe Morris did update something else without noticing
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/45845308/b5b61630-771a-48e2-9f47-7eeb0d647b23)

**Comment by tetsuoo-online** [comment]
ok upgrading Python is alreazdy a headache, couldn't find the way. Why all the pain... lol

**Comment by MorrisLu-Taipei** [comment]
Have you installed these below before gradio

source ./venv/bin/activate
pip install --upgrade pip
pip install nvidia-cudnn-cu11==8.9.4.25 --no-cache-dir
pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==9.0.1.post11.dev4 --no-cache-dir
pip uninstall -y nvidia-cudnn-cu11
pip install onnxruntime
pip install colored

**Comment by HesamAlef** [comment]
I have exactly this problem. Exactly as @lingtingfengyu  said.
I'm using the 1.6 stable release. And I think it's because it only supports version 1.5 and 2.1!
If it is other than this please let me know

**Comment by nozomu0321** [comment]
How do I update Gradio?
I have run the command as shown below and it appears to be working correctly.
However, when I look at it on the web, it is still at 3.32 and has not been updated.

(venv) J:\sd150\stable-diffusion-webui>pip install --upgrade gradio
～～～～～
Installing collected packages: gradio
Attempting uninstall: gradio
Found existing installation: gradio 3.32.0
Uninstalling gradio-3.32.0: Successfully uninstalled gradio-3.32.0
Successfully uninstalled gradio-3.32.0
Successfully installed gradio-3.50.2

**Comment by nozomu0321** [comment]
I was able to solve the above problem.
In the end I could not figure out how to update gradio, but by upgrading stable diffusion to v1.6.0, gradio is now working as it is v3.41.0.

**Comment by HesamAlef** [comment]
> I was able to solve the above problem. In the end I could not figure out how to update gradio, but by upgrading stable diffusion to v1.6.0, gradio is now working as it is v3.41.0.

-----------------

Are u sure ?

**Comment by nozomu0321** [comment]
Sorry, I may have misunderstood that Stable diffusion itself is v1.6 and the version of Stable diffusion Web UI.

**Comment by MorrisLu-Taipei** [comment]
How to upgrade your gradio in webui a1111 just simplely modify file and restart webui again
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/22585297/b6bc9466-ed31-47bd-bc7b-2eca7d716a9a)

**Comment by MorrisLu-Taipei** [comment]
Yes , my vesion is a1111==1.52 and gradio==3.41

**Comment by NoteToSelfFindGoodNickname** [comment]
Not working even with gradio 3.41.2

**Comment by Acephalia** [comment]
Same issue. Tried everything including reinstalling from scratch. I can generate for base 1.5 but no other models work including SDXL base. Just gives me the same error No ONNX found.

**Comment by indiana2021** [comment]
the problem is the arg --medvram, remove it from webuser.bat and you can use rt profiles

**Comment by kx-kexi** [comment]
the problem still cannot be solved by updating the gradio==3.41.0. what can i do?please help me,thank you very much

**Comment by kx-kexi** [comment]
> the problem still cannot be solved by updating the gradio==3.41.0. what can i do?please help me,thank you very much

i solve this problem by change the opset from 17 to 14

**Comment by tetsuoo-online** [comment]
> Have you installed these below before gradio
> 
> source ./venv/bin/activate pip install --upgrade pip pip install nvidia-cudnn-cu11==8.9.4.25 --no-cache-dir pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==9.0.1.post11.dev4 --no-cache-dir pip uninstall -y nvidia-cudnn-cu11 pip install onnxruntime pip install colored

I'm a bit confused with your syntax, are you on Linux ? I don't have a 'bin' folder, activate is in Scripts for me
Another confusing thing, you first install nvidia-cudnn, then tensorrt, then you uninstall nvidia-cudnn that you just installed, I don't get it. Why ?

**Comment by mrfood0** [comment]
Had this issue, fixed it by removing all my cmd COMMANDLINE_ARGS
Which were:  --api --xformers

**Comment by isawwxkrcv** [comment]
First of all, you have to use the 512X512 basic setup and run it once to get the ONNX file, then set up the specs you want.
