### ISSUE TITLE
Bad allocation error 

### ISSUE THREAD

**Issue by No-Tips** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#98]
So after trying to export default engine for a checkpoint i get this errorlog

`ERROR:root:bad allocation
Traceback (most recent call last):
  File "D:\Neurostuff\Stable Diffusion\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 84, in export_onnx
    torch.onnx.export(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\torch\onnx\utils.py", line 1587, in _export
    ) = graph._export_onnx(  # type: ignore[attr-defined]
MemoryError: bad allocation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Neurostuff\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Neurostuff\Stable Diffusion\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 134, in export_unet_to_trt
    export_onnx(
  File "D:\Neurostuff\Stable Diffusion\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 130, in export_onnx
    exit()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None`

I've tried to reinstall venv and disabling diable_optimizations, no luck. My GPU is RTX 4060TI

**Comment by MorkTheOrk** [comment]
Do you have any CLI ARGs for auto1111? Have you tried disableing them?

**Comment by MorkTheOrk** [comment]
also what model are you trying to export? What are your system specs?

**Comment by No-Tips** [comment]
> Do you have any CLI ARGs for auto1111? Have you tried disableing them?

I've tried to export this model: https://civitai.com/models/7240/meinamix

I have no CLI args, all my specs are here: https://pastebin.com/9gFDUhFR
